apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-langgraph-agent
  namespace: churn-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-agent
  template:
    metadata:
      labels:
        app: rag-agent
    spec:
      containers:
      - name: agent-container
        image: punit19/rag-langgraph-agent:5e69ba69845679cb19de7950eddeca310549e532
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: llmops-secrets
              key: OPENAI_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: rag-langgraph-service
  namespace: churn-model
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: rag-agent